name: flutter_polyline_points
description: A flutter package to get polyline points by either passing the coordinates or google encoded polyline string
version: 1.0.0
homepage: https://github.com/Dammyololade/flutter_polyline_points

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
